# playbook.yml

- hosts: webservers
  become: yes
  tasks:
    # Install base prerequisites (system utilities, nginx already pulled in role)
    - name: Install system packages
      apt:
        name:
          - python3
          - rsync
        state: present
        update_cache: yes
        cache_valid_time: 3600

- hosts: webservers
  become: yes
  roles:
    - mongodb
    - node
    - nginx
